language: ruby
rvm:
  - 1.9.3
  - 2.1
  - 2.2
env:
  - CHEF_VERSION=10.34.6
  - CHEF_VERSION=11.16.4
  - CHEF_VERSION=12.0.3
before_script:
  - chef-client --version
notifications:
  email: false
sudo: false
